# Project Overview
**Predictive Modeling in Agriculture: Crop Recommendation**

**Business Problem:**

A farmer wants to determine the most suitable crop to grow on a particular field based on soil conditions.

However, due to budget constraints, the farmer can only afford to measure four soil properties:

* Nitrogen (N)
* Phosphorous (P)
* Potassium (K)
* Soil pH

The objective is to determine **which of these soil measures provides the most useful information for predicting the appropriate crop**.

**Project Objective:**

Build a machine learning classification model to predict crop yield per farm per season (a regression problem).

## Extract & Load

> The source data is in loose CSV files outside any database; this stage loads the files into DuckDB's `raw` schema. This is the 'EL' in ELT; no cleaning is done at this stage; it is done in the next stage, within the database using SQL.

### Connect to DuckDB; create the schemas

In [21]:
# Import libraries & dependencies
import duckdb
import pandas as pd
from pathlib import Path
import sys, shutil

# Mount drive and specify path
try:
  # Running in Colab
  from google.colab import drive
  drive.mount('/content/drive/')
  project_dir = Path('/content/drive/MyDrive/Agriculture_ELT')
  db_path = Path('/content/agric_elt.duckdb')
except ImportError:
  # Running locally
  project_dir = Path('..')
  db_path = project_dir / 'data' / 'agric_elt.duckdb'

source_dir = project_dir / 'data'

print('Source folder exists:', source_dir.exists())
print(sorted(p.name for p in source_dir.glob("*.csv")))

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
Source folder exists: True
['farms.csv', 'harvests.csv', 'inputs.csv', 'plantings.csv', 'weather.csv']

In [22]:
# Connect to db and create schemas
conn = duckdb.connect(str(db_path))

conn.sql("CREATE SCHEMA IF NOT EXISTS raw")
conn.sql("CREATE SCHEMA IF NOT EXISTS staging")
conn.sql("CREATE SCHEMA IF NOT EXISTS marts")

conn.sql(
    "SELECT schema_name from information_schema.schemata WHERE schema_name IN ('raw', 'staging', 'marts')"
).df()

  schema_name
0       marts
1         raw
2     staging

### Load CSV files into `raw` as text.

> Read every column as `VARCHAR` to avoid altering data or load failure; keeping all records as text ensures nothing is lost or altered. Data types will be transformed appropriately in the next stage.
> Two columns are added to each table: source_file (where each row came from) and loaded_at (when it was loaded).

In [23]:
tables = ['farms', 'plantings', 'inputs', 'harvests', 'weather']

for name in tables:
  conn.sql(
      f"""
      CREATE OR REPLACE TABLE raw.{name} AS
      SELECT
        *,
        '{name}.csv' AS source_file,
        current_timestamp AS loaded_at
      FROM read_csv("{source_dir / (name + '.csv')}", header=true, all_varchar=true)
      """
  )

  print(f"loaded raw.{name}")

loaded raw.farms
loaded raw.plantings
loaded raw.inputs
loaded raw.harvests
loaded raw.weather

### Check & Validate Loading Stage

> Check every table's row count matches the no. of rows in corresponding CSV.

In [24]:
checks = []

for name in tables:
  in_db = conn.sql(f"SELECT COUNT(*) FROM raw.{name}").fetchone()[0]
  in_csv = len(pd.read_csv(source_dir / f'{name}.csv', dtype=str))
  checks.append(
      {
          'table': name,
          'rows_in_db': in_db,
          'rows_in_csv': in_csv,
          'match': in_db == in_csv
      }
  )

result = pd.DataFrame(checks)
assert result['match'].all(), "Row count differ between CSV and db!"
result

       table  rows_in_db  rows_in_csv  match
0      farms         812          812   True
1  plantings        5377         5377   True
2     inputs        7009         7009   True
3   harvests        5014         5014   True
4    weather       19078        19078   True

### Preview the raw data

In [25]:
for name in tables:
  print(f'raw.{name}')
  display(conn.sql(f"SELECT * EXCLUDE (source_file, loaded_at) FROM raw.{name} LIMIT 5").df())
  print('\n')

raw.farms

  farm_id       county size_acres  soil_type irrigated registration_date
0  F-0001     Kakamega  0.6 acres  clay loam        no        29/03/2020
1   F0002  Uasin Gishu       11.1       loam         N        2012-05-06
2   F0003         Meru        1.0       clay         N        2021-04-14
3   F0004         Meru        1.3      Sandy         N        13/11/2008
4   F0005        Narok        6.2  clay loam        No        2021-03-29

raw.plantings

,planting_id,farm_id,season,crop,planting_date,seed_variety,area_planted_acres
0,P00001,f0001,2020-LR,Maize,2020-03-28,H513,0.9
1,P00002,F0001,2023 Long Rains,Beans,"Apr 24, 2023",Local,0.3
2,P00003,F0001,2024 LR,Maize,18/04/2024,LOCAL,0.6
3,P00004,F0002,LR 2019,Maize,2019-03-14,DK8031,8.2
4,P00005,F0002,SR2019,Wheat,18/10/2019,Robin,4.7

raw.inputs

  input_id farm_id application_date   input_type quantity    unit cost_kes
0   I00001   F0001       2020-03-23       manure    300.0      Kg     1247
1   I00002   F0001       2024-04-18  DAP 18-46-0     30.0     kgs     4263
2   I00003   F0001       31/05/2024          CAN     24.0      kg     None
3   I00004   F0002       2019-03-14  DAP 18-46-0    410.0      kg     None
4   I00005   F0002       02/05/2019    Pesticide      7.5  litres     8521

raw.harvests

,harvest_id,farm_id,season,crop,harvest_date,yield_qty,yield_unit,notes
0,H00001,F0001,2023 LR,beans,24/07/2023,0.5,bags,None
1,H00002,F0001,2024 Long Rains,Maize,22/08/2024,5.7,bags,None
2,H00003,F0002,2019 Long Rains,Maize,2019-08-11,13.15,tonnes,None
3,H00004,F0002,2019 Short Rains,Wheat,19/02/2020,8.91,t,None
4,H00005,F0002,2020 LR,wheat,08/07/2020,6.94,MT,None

raw.weather

         date  county rainfall_mm temp_max_c temp_min_c
0  2019-01-01  Kisumu         0.0       28.2       16.4
1  2019-01-02  Kisumu         0.0       27.7       15.5
2  2019-01-03  Kisumu         0.0       29.4       15.5
3  2019-01-04  Kisumu         0.0       29.9       16.6
4  2019-01-05  Kisumu         0.0       28.4       15.9

### How messy is the data?

> Now that we have loaded the data successfully into the db, let's preview the messiness of the data.

In [26]:
# 1. Same crop name, different spelling formats.
conn.sql(
    """
      SELECT crop,
          COUNT(*) as count
      FROM raw.harvests
      GROUP BY 1
      ORDER BY 2 DESC
    """
).df()

           crop  count
0         Maize   1836
1         Beans   1028
2         Wheat    408
3       Sorghum    390
4         maize    294
5         MAIZE    161
6         beans    154
7          Corn    126
8        Maize     114
9         wheat     73
10         Bean     73
11        BEANS     71
12      sorghum     63
13       Beans      60
14      SORGHUM     37
15  Wheat grain     30
16     Sorghum      30
17        WHEAT     26
18       Sorgum     21
19       Wheat      19

In [27]:
# 2. Harvest yeilds in different formats
conn.sql(
    """
      SELECT yield_unit,
        COUNT(*) AS count
      FROM raw.harvests
      GROUP BY 1
      ORDER BY 2 DESC
    """
).df()

   yield_unit  count
0        bags   1642
1          kg   1039
2        Bags    568
3         bag    385
4          Kg    330
5      tonnes    282
6    90kg bag    212
7          KG    190
8         kgs    141
9        None     84
10          t     84
11         MT     57

In [28]:
# 3. Explore messiness in weather table
conn.sql(
    """
      SELECT rainfall_mm,
        COUNT(*) AS count
      FROM raw.weather
      WHERE TRY_CAST(rainfall_mm AS FLOAT) IS NULL OR TRY_CAST(rainfall_mm AS FLOAT) < 0
      GROUP BY 1
      ORDER BY 2 DESC
    """
).df()

  rainfall_mm  count
0        None    420
1       trace    135
2        -999     75

This stage outputs an `agric_elt.duckdb` with fuve tables in the `raw` schema identical to the source CSV files. The `.duckdb` file is git-ignored since re-running the notebook rebuilds the file.

## Staging: Data Transformations

> The `raw` tables are too messy to be joined and analyzed reliably. This stage turns each `raw.*` table into a clean, analysis-ready `staging.*` table using SQL.

> This stage represents the T in 'ELT' and the tranformations happen inside the database without modifing the `raw` schema.

In [29]:
# Preview the tables in raw schema
conn.sql(
    """
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema == 'raw'
      ORDER BY 1
    """
).df()

  table_name
0      farms
1   harvests
2     inputs
3  plantings
4    weather

### Reusable Cleaning Functions

> There are fields that appear in all five tables eg fields IDs and dates; we will define SQL functions to reuse across all tables.

In [30]:
# Farms IDS: Standardise spelling formats e.g f0002, F-0002 and "F0002 " >> become F0002
conn.sql(
    """
      CREATE OR REPLACE MACRO clean_farm_id(x) AS
        upper(regexp_replace(trim(x), '[^A-Za-z0-9]', '', 'g'))
    """
)

# Correct misspelt crop names; aliases such as corn should be tranformed to maize
conn.sql(
    """
      CREATE OR REPLACE MACRO clean_crop(x) AS
        CASE lower(trim(x))
          WHEN 'corn' THEN 'maize'
          WHEN 'bean' THEN 'beans'
          WHEN 'sorgum' THEN 'sorghum'
          WHEN 'wheat grain' THEN 'wheat'
          ELSE lower(trim(x))
        END
    """
)

# Standardize county names
# County names
conn.sql("""
    CREATE OR REPLACE MACRO clean_county(x) AS
        CASE lower(replace(trim(x), '-', ' '))
            WHEN 'kisumu' THEN 'Kisumu'
            WHEN 'nakuru' THEN 'Nakuru'
            WHEN 'uasin gishu' THEN 'Uasin Gishu'
            WHEN 'kakamega' THEN 'Kakamega'
            WHEN 'machakos' THEN 'Machakos'
            WHEN 'meru' THEN 'Meru'
            WHEN 'bungoma' THEN 'Bungoma'
            WHEN 'narok' THEN 'Narok'
        END
""")

# Varying season labels:
# '2023 Long Rains', 'LR2023', '2023 LR' e.t.c >> become 2023-LR
conn.sql(
    """
      CREATE OR REPLACE MACRO clean_season(x) AS
        regexp_extract(x, '[0-9]{4}', 0) || '-' ||
        CASE WHEN lower(x) LIKE '%short%' OR upper(x) LIKE '%SR%' THEN 'SR'
             WHEN lower(x) LIKE '%long%' OR upper(x) LIKE '%LR%' THEN 'LR'
        END
    """
)

# Clean and standardize date formats
conn.sql(
    """
      CREATE OR REPLACE MACRO parse_date(x) AS
        CAST(COALESCE(
            TRY_STRPTIME(x, '%Y-%m-%d'),
            TRY_STRPTIME(x, '%d/%m/%Y'),
            TRY_STRPTIME(x, '%d-%b-%y'),
            TRY_STRPTIME(x, '%b %d, %Y')
        ) AS Date)
    """
)

# Quick test
conn.sql(
    """
      SELECT clean_farm_id('f-0005 ') AS farm_id,
        clean_crop('corn') AS crop,
        clean_season('2023 Long Rains') AS season,
        parse_date('14-Sep-26') AS date_1,
        parse_date('2021-03-21') AS date_2
    """
).df()

  farm_id   crop   season     date_1     date_2
0   F0005  maize  2023-LR 2026-09-14 2021-03-21

### Clean & Transform `farms` table.

In [31]:
# Preview & inspect raw.farms table
conn.sql(
    """
    SELECT *
    EXCLUDE (source_file, loaded_at)
    FROM raw.farms
    LIMIT 5
    """
).df()

  farm_id       county size_acres  soil_type irrigated registration_date
0  F-0001     Kakamega  0.6 acres  clay loam        no        29/03/2020
1   F0002  Uasin Gishu       11.1       loam         N        2012-05-06
2   F0003         Meru        1.0       clay         N        2021-04-14
3   F0004         Meru        1.3      Sandy         N        13/11/2008
4   F0005        Narok        6.2  clay loam        No        2021-03-29

In [32]:
# Check for duplicates
conn.sql(
    """
    SELECT farm_id,
      COUNT(*) AS occurrence_count
    FROM raw.farms
    GROUP BY 1
    HAVING occurrence_count > 1
    """
).df()

  farm_id  occurrence_count
0   F0009                 2
1   F0243                 2
2   F0431                 2
3   F0736                 2
4   F0765                 2
5   F0112                 2
6   F0176                 2
7   F0256                 2
8   F0511                 2
9   F0643                 2

In [33]:
# Inspect the duplicates further
conn.sql(
    """
    SELECT *
    EXCLUDE (source_file, loaded_at)
      FROM raw.farms
      WHERE farm_id IN ('F0643', 'F0256', 'F0431')
      ORDER BY farm_id
    """
).df()

# VERDICT: The records are clearly duplicated; they should be dropped from the table.

  farm_id    county size_acres  soil_type irrigated registration_date
0   F0256    Nakuru        5.4  clay loam         0        2012-12-30
1   F0256    Nakuru  5.4 acres  clay loam         N        30/12/2012
2   F0431      Meru        1.2      Sandy         N        2018-11-29
3   F0431      Meru        1.2      sandy         N        2018-11-29
4   F0643  machakos        4.6       loam         N        2010-11-16
5   F0643  Machakos        4.6       loam        No        16/11/2010

**Cleaning Issues:**

*   `farm_id` in different formats.
*   Duplicates in `farm_id` column.
*   `county` & `soil_type` in varying case fromats.
*   `size_acres` in varying units (acres and hectares).
*   Different `registration_date` formats.
*   `irrigated` assigned different flags: N, Y, no, Yes, 1.


> **Cleaning Actions:** clean the IDs and remove duplicates, convert sizes to acres (1 ha = 2.471 acres), turn the irrigation flag into a true/false value, & standardise soil type and county. Missing soil types stay `NULL`.

In [34]:
# Cleaning transformations
conn.sql("""
    CREATE OR REPLACE TABLE staging.farms AS
    WITH cleaned AS (
        SELECT
            clean_farm_id(r.farm_id) AS farm_id,
            clean_county(r.county) AS county,
            ROUND(
                TRY_CAST(regexp_extract(r.size_acres, '[0-9]+[.]?[0-9]*', 0) AS DOUBLE)
                * CASE WHEN lower(r.size_acres) LIKE '%ha%' THEN 2.471 ELSE 1 END
            , 1)                      AS size_acres,
            CASE lower(replace(trim(r.soil_type), '-', ' '))
                WHEN 'loamy' THEN 'loam'
                ELSE NULLIF(lower(replace(trim(r.soil_type), '-', ' ')), '')
            END                       AS soil_type,
            CASE lower(trim(r.irrigated))
                WHEN 'y' THEN TRUE  WHEN 'yes' THEN TRUE  WHEN '1' THEN TRUE
                WHEN 'n' THEN FALSE WHEN 'no'  THEN FALSE WHEN '0' THEN FALSE
            END                       AS irrigated,
            parse_date(r.registration_date) AS registration_date,
            r.rowid                   AS _row
        FROM raw.farms r
    ),
    ranked AS (
        SELECT *,
          ROW_NUMBER() OVER (PARTITION BY farm_id ORDER BY _row) AS rn
        FROM cleaned
    )
    SELECT farm_id, county, size_acres, soil_type, irrigated, registration_date
    FROM ranked
    WHERE rn = 1
""")

conn.sql("SELECT * FROM staging.farms LIMIT 5").df()

  farm_id    county  size_acres   soil_type  irrigated registration_date
0   F0006    Kisumu         4.0        clay      False        2015-12-04
1   F0019      Meru         6.8   clay loam      False        2013-10-11
2   F0029  Kakamega         0.8   clay loam       True        2019-10-22
3   F0049    Nakuru         2.9  sandy loam      False        2010-04-18
4   F0066  Kakamega         2.1        loam      False        2013-10-12

### Clean & Transform `plantings` table

In [35]:
# Preview & inspect raw.plantings table
conn.sql(
    """
    SELECT *
      EXCLUDE (source_file, loaded_at)
    FROM raw.plantings
    LIMIT 5
    """
).df()

,planting_id,farm_id,season,crop,planting_date,seed_variety,area_planted_acres
0,P00001,f0001,2020-LR,Maize,2020-03-28,H513,0.9
1,P00002,F0001,2023 Long Rains,Beans,"Apr 24, 2023",Local,0.3
2,P00003,F0001,2024 LR,Maize,18/04/2024,LOCAL,0.6
3,P00004,F0002,LR 2019,Maize,2019-03-14,DK8031,8.2
4,P00005,F0002,SR2019,Wheat,18/10/2019,Robin,4.7

In [36]:
# Check for duplicates in planting_id
conn.sql(
    """
    SELECT COUNT(*) total_duplicates
    FROM
      (SELECT planting_id,
        COUNT(*) AS occurrence_count
      FROM raw.plantings
      GROUP BY 1
      HAVING occurrence_count > 1) AS sub
    """
).df()

   total_duplicates
0                79

In [37]:
# Inspect the duplicates further
conn.sql(
    """
    SELECT *
    EXCLUDE (source_file, loaded_at)
      FROM raw.plantings
      WHERE planting_id IN ('P04938', 'P04226', 'P00208')
      ORDER BY planting_id
    """
).df()

# VERDICT: Duplicated farm_ids contain similar data with different input formats;
# duplicates will be dropped from the table.

,planting_id,farm_id,season,crop,planting_date,seed_variety,area_planted_acres
0,P00208,F0033,2020 Short Rains,Maize,2020-11-20,local,0.9
1,P00208,F0033,2020 Short Rains,Maize,20/11/2020,local,0.9
2,P04226,F0637,2024 Long Rains,MAIZE,2024-03-19,landrace,3.6
3,P04226,F0637,2024 LR,Maize,19/03/2024,local,None
4,P04938,F0747,2024-LR,Maize,2024-04-01,local,1.1
5,P04938,F0747,2024 long rains,Maize,2024-04-01,Local,1.1

In [38]:
# Missing values in seed_variety col
conn.sql(
    """
    SELECT COUNT(*) AS seed_variety_nulls
    FROM
      (SELECT *
      FROM raw.plantings
      WHERE seed_variety IS NULL) AS sub
    """
).df()

   seed_variety_nulls
0                 329

**Cleaning Issues:**
*   Duplicated records in `planting_id`.
*   `farm_id`, `season` & `planting_date` in varying formats.
*   `seed_variety` == Local have varying spelling formats. Landrace variety is also a local variety.
*   Missing values in `seed_variety`.
*   Crop names have different spellings.

**Cleaning Actions:**
*   Standardise `season`, `crop`, `seed_variety`.
*   Group the local-seed spellings.
*   Parse `planting_date`.
*   All local `seed_variety` to be flagged as not certified.

In [39]:
# Clean & transform ops
conn.sql("""
    CREATE OR REPLACE TABLE staging.plantings AS
    WITH cleaned AS (
        SELECT
            r.planting_id,
            clean_farm_id(r.farm_id) AS farm_id,
            clean_season(r.season) AS season,
            clean_crop(r.crop) AS crop,
            parse_date(r.planting_date) AS planting_date,
            CASE WHEN lower(trim(r.seed_variety)) IN ('local', 'landrace') THEN 'local'
                 ELSE NULLIF(trim(r.seed_variety), '')
            END AS seed_variety,
            TRY_CAST(r.area_planted_acres AS DOUBLE) AS area_planted_acres,
            r.rowid AS _row
        FROM raw.plantings r
    ),
    ranked AS (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY planting_id ORDER BY _row) AS rn
        FROM cleaned
    )
    SELECT
        planting_id,
        farm_id,
        season,
        CAST(split_part(season, '-', 1) AS INTEGER) AS season_year,
        split_part(season, '-', 2) AS season_type,
        crop,
        planting_date,
        seed_variety,
        CASE WHEN seed_variety IS NULL THEN NULL
             WHEN seed_variety = 'local' THEN FALSE
             ELSE TRUE END AS certified_seed,
        area_planted_acres
    FROM ranked
    WHERE rn = 1
      AND farm_id IN (SELECT farm_id FROM staging.farms)
""")

conn.sql("SELECT * FROM staging.plantings LIMIT 5").df()

,planting_id,farm_id,season,season_year,season_type,crop,planting_date,seed_variety,certified_seed,area_planted_acres
0,P00017,F0003,2023-LR,2023,LR,maize,2023-03-20,local,False,0.9
1,P00041,F0007,2021-LR,2021,LR,beans,2021-04-04,local,False,0.9
2,P00053,F0008,2023-SR,2023,SR,maize,2023-10-03,H513,True,3.8
3,P00054,F0008,2024-SR,2024,SR,wheat,2024-10-31,Robin,True,5.0
4,P00078,F0012,2024-LR,2024,LR,maize,2024-03-20,PH4,True,0.7

### Clean & Transform inputs table

In [40]:
# Preview raw.inputs table
conn.sql(
    """
    SELECT *
      EXCLUDE (source_file, loaded_at)
    FROM raw.inputs
    LIMIT 5;
    """
).df()

  input_id farm_id application_date   input_type quantity    unit cost_kes
0   I00001   F0001       2020-03-23       manure    300.0      Kg     1247
1   I00002   F0001       2024-04-18  DAP 18-46-0     30.0     kgs     4263
2   I00003   F0001       31/05/2024          CAN     24.0      kg     None
3   I00004   F0002       2019-03-14  DAP 18-46-0    410.0      kg     None
4   I00005   F0002       02/05/2019    Pesticide      7.5  litres     8521

In [41]:
# Explore duplicates in input_id
conn.sql(
    """
    SELECT COUNT(*) AS total_duplicates
    FROM
      (SELECT input_id,
        COUNT(input_id) AS occurrence_count
      FROM raw.inputs
      GROUP BY 1
      HAVING occurrence_count > 1) AS sub
    """
).df()

   total_duplicates
0                83

In [42]:
# Explore the duplicates further
conn.sql(
    """
    SELECT *
      EXCLUDE (source_file, loaded_at)
    FROM raw.inputs
    WHERE input_id IN ('I00233', 'I00405', 'I06788')
    ORDER BY input_id
    """
).df()

# VERDICT: Remove duplicated records.

  input_id farm_id application_date input_type quantity  unit cost_kes
0   I00233   F0030        17-May-19        can     55.0   kgs     4480
1   I00233   F0030       2019-05-17        CAN     55.0    kg     4480
2   I00405   F0048       2023-11-13       Urea    155.0    kg    19763
3   I00405   F0048       2023-11-13       Urea    155.0    kg    19763
4   I06788   F0783     Mar 06, 2022        DAP      1.6  bags     9021
5   I06788   F0783       2022-03-06        DAP      1.6  Bags     None

**Cleaning Issues:**
*   `application_date` in different formats.
*   `input_type` in varying formats: e.g DAP, dap, CAN, CAN(top dress).
*   Different `unit` formats e.g bags, Bags, 50kg bag, kg, KG.
*   `farm_id` in varying formats e.g f0127, F0305.
*   Some values `cost_kes` are in text and NONE formats.



**Cleaning Actions:**
*   Parse `application_date`.
*   Standadise `input_type`, & `farm_id`.
*   Convert quantities to a single unit: kg for solids (a fertilizer bag = 50 kg) and litres for liquids. When the unit is missing the quantity is left as NULL.
*   Map every `input_type` to one category (DAP, CAN, Urea, Manure, Pesticide)

In [43]:
# Clean & transform ops
conn.sql("""
    CREATE OR REPLACE TABLE staging.inputs AS
    WITH cleaned AS (
        SELECT
            r.input_id,
            clean_farm_id(r.farm_id) AS farm_id,
            parse_date(r.application_date) AS application_date,
            CASE
                WHEN lower(trim(r.input_type)) LIKE 'dap%' THEN 'DAP'
                WHEN lower(trim(r.input_type)) LIKE 'can%' THEN 'CAN'
                WHEN lower(trim(r.input_type)) LIKE 'urea%' THEN 'Urea'
                WHEN lower(trim(r.input_type)) LIKE 'manure%'
                  OR lower(trim(r.input_type)) IN ('fym')
                  OR lower(trim(r.input_type)) LIKE 'farmyard%' THEN 'Manure'
                WHEN lower(trim(r.input_type)) LIKE 'pesticide%'
                  OR lower(trim(r.input_type)) LIKE 'duduthrin%'
                  OR lower(trim(r.input_type)) LIKE 'insecticide%' THEN 'Pesticide'
            END                              AS input_type,
            TRY_CAST(r.quantity AS DOUBLE)   AS quantity_raw,
            CASE
                WHEN lower(trim(r.unit)) IN ('kg', 'kgs') THEN 'kg'
                WHEN lower(trim(r.unit)) IN ('bag', 'bags', '50kg bag') THEN 'bags'
                WHEN lower(trim(r.unit)) IN ('t', 'tonnes', 'mt') THEN 'tonnes'
                WHEN lower(trim(r.unit)) IN ('l', 'litres', 'ltrs') THEN 'litres'
                WHEN lower(trim(r.unit)) = 'ml' THEN 'ml'
            END AS unit_raw,
            TRY_CAST(regexp_replace(r.cost_kes, '[^0-9.]', '', 'g') AS DOUBLE) AS cost_kes,
            r.rowid AS _row
        FROM raw.inputs r
    ),
    ranked AS (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY input_id ORDER BY _row) AS rn
        FROM cleaned
    )
    SELECT
        input_id,
        farm_id,
        application_date,
        input_type,
        CASE WHEN input_type IN ('DAP', 'CAN', 'Urea') THEN 'fertilizer'
             WHEN input_type = 'Manure' THEN 'manure'
             WHEN input_type = 'Pesticide' THEN 'pesticide'
        END AS input_group,
        CASE unit_raw
            WHEN 'kg' THEN quantity_raw
            WHEN 'bags' THEN quantity_raw * 50
            WHEN 'tonnes' THEN quantity_raw * 1000
            WHEN 'litres' THEN quantity_raw
            WHEN 'ml' THEN quantity_raw / 1000
        END AS quantity,
        CASE WHEN unit_raw IN ('kg', 'bags', 'tonnes') THEN 'kg'
             WHEN unit_raw IN ('litres', 'ml') THEN 'litres'
        END AS unit,
        cost_kes
    FROM ranked
    WHERE rn = 1
      AND farm_id IN (SELECT farm_id FROM staging.farms)
""")

conn.sql("SELECT * FROM staging.inputs LIMIT 5").df()

,input_id,farm_id,application_date,input_type,input_group,quantity,unit,cost_kes
0,I00003,F0001,2024-05-31,CAN,fertilizer,24.0,kg,NaN
1,I00015,F0003,2019-06-05,Pesticide,pesticide,0.5,litres,749.0
2,I00048,F0006,2023-10-14,DAP,fertilizer,77.5,kg,11871.0
3,I00058,F0007,2024-05-22,Urea,fertilizer,45.0,kg,5175.0
4,I00059,F0008,2019-03-29,DAP,fertilizer,305.0,kg,36986.0

### Clean & Transform harvests table

In [44]:
# Preview raw.harvests table
conn.sql(
    """
    SELECT *
      EXCLUDE (source_file, loaded_at)
    FROM raw.harvests
    LIMIT 5;
    """
).df()

,harvest_id,farm_id,season,crop,harvest_date,yield_qty,yield_unit,notes
0,H00001,F0001,2023 LR,beans,24/07/2023,0.5,bags,None
1,H00002,F0001,2024 Long Rains,Maize,22/08/2024,5.7,bags,None
2,H00003,F0002,2019 Long Rains,Maize,2019-08-11,13.15,tonnes,None
3,H00004,F0002,2019 Short Rains,Wheat,19/02/2020,8.91,t,None
4,H00005,F0002,2020 LR,wheat,08/07/2020,6.94,MT,None

In [45]:
# Explore yield_qty; some quantities are negative.
conn.sql(
    """
    SELECT yield_qty
    FROM raw.harvests
    WHERE (yield_qty::FLOAT) < 0
    LIMIT 5;
    """
).df()

  yield_qty
0     -27.8
1      -7.5
2      -0.5
3     -37.3
4     -88.4

In [46]:
# Explore null values in yield_qty
conn.sql(
    """
    SELECT COUNT(*) AS null_count
    FROM
      (SELECT yield_qty
      FROM raw.harvests
      WHERE yield_qty IS NULL) AS sub;
    """
).df()

   null_count
0         105

In [47]:
# Explore no. of duplicates in harvest_id
conn.sql(
    """
    SELECT COUNT(*) AS total_duplicates
    FROM
      (SELECT harvest_id,
        COUNT(harvest_id) AS occurrence_count
      FROM raw.harvests
      GROUP BY 1
      HAVING occurrence_count > 1) AS sub
    """
).df()

   total_duplicates
0                74

In [48]:
# Investigate the duplicates further
conn.sql(
    """
    SELECT *
      EXCLUDE ('source_file', 'loaded_at')
    FROM raw.harvests
    WHERE harvest_id IN ('H00043', 'H00374', 'H00349')
    ORDER BY 1
    """
).df()

# VERDICT: Duplicates are errorneous and should be dropped.

,harvest_id,farm_id,season,crop,harvest_date,yield_qty,yield_unit,notes
0,H00043,F0008,2019 Long Rains,Wheat,2019-08-06,12649.0,Kg,None
1,H00043,F0008,2019-LR,Wheat,06/08/2019,12649.0,Kg,None
2,H00349,F0057,2019 long rains,maize,2019-07-28,8.7,Bags,None
3,H00349,F0057,LR 2019,Corn,28/07/2019,-8.7,bags,None
4,H00374,F0060,2021 SR,Maize,2022-02-28,12.0,bags,None
5,H00374,F0060,2021 Short Rains,Maize,2022-02-28,12.0,bags,None

**Cleaning Issues:**
*   `farm_id`, `harvest_date` & `season` in varying formats.
*   Duplicated records in `harvest_id`.
*   Different spellings in `crop`.
*   Yields in varying units: kg, bags (90 kg) or tonnes
*   `yield_qty` have negative and null values.

**Cleaning Actions:**
*   Standardise `farm_id`, `harvest_date` & `season`.
*   Make `crop` spellings uniform.
*   Drop duplicates in `harvest_id`.
*   Convert every yield to kgs in a new yield_kg column (keep the original quantity and unit for reference).
*   Set negative yields to NULL.

In [49]:
# Clean & tranformations ops
conn.sql("""
    CREATE OR REPLACE TABLE staging.harvests AS
    WITH cleaned AS (
        SELECT
            r.harvest_id,
            clean_farm_id(r.farm_id) AS farm_id,
            clean_season(r.season) AS season,
            clean_crop(r.crop) AS crop,
            parse_date(r.harvest_date) AS harvest_date,
            CASE WHEN TRY_CAST(r.yield_qty AS DOUBLE) < 0 THEN NULL
                 ELSE TRY_CAST(r.yield_qty AS DOUBLE) END AS yield_qty,
            CASE
                WHEN lower(trim(r.yield_unit)) IN ('kg', 'kgs') THEN 'kg'
                WHEN lower(trim(r.yield_unit)) IN ('bag', 'bags', '90kg bag') THEN 'bags'
                WHEN lower(trim(r.yield_unit)) IN ('t', 'tonnes', 'mt') THEN 'tonnes'
            END AS yield_unit,
            NULLIF(lower(trim(r.notes)), '') AS notes,
            r.rowid AS _row
        FROM raw.harvests r
    ),
    ranked AS (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY harvest_id ORDER BY _row) AS rn
        FROM cleaned
    )
    SELECT
        harvest_id,
        farm_id,
        season,
        CAST(split_part(season, '-', 1) AS INTEGER) AS season_year,
        split_part(season, '-', 2) AS season_type,
        crop,
        harvest_date,
        yield_qty,
        yield_unit,
        CASE yield_unit
            WHEN 'kg' THEN yield_qty
            WHEN 'bags' THEN yield_qty * 90
            WHEN 'tonnes' THEN yield_qty * 1000
        END AS yield_kg,
        notes
    FROM ranked
    WHERE rn = 1
      AND farm_id IN (SELECT farm_id FROM staging.farms)
""")

conn.sql("SELECT * FROM staging.harvests LIMIT 5").df()

,harvest_id,farm_id,season,season_year,season_type,crop,harvest_date,yield_qty,yield_unit,yield_kg,notes
0,H00003,F0002,2019-LR,2019,LR,maize,2019-08-11,13.15,tonnes,13150.0,None
1,H00055,F0009,2020-SR,2020,SR,sorghum,2021-02-21,12.90,bags,1161.0,None
2,H00082,F0013,2023-LR,2023,LR,beans,2023-06-19,0.70,bags,63.0,None
3,H00102,F0017,2019-LR,2019,LR,wheat,2019-07-14,4033.00,kg,4033.0,None
4,H00110,F0018,2019-SR,2019,SR,maize,2020-03-18,3.10,bags,279.0,None

### Clean & Transform weather table

In [50]:
# Preview raw.weather table
conn.sql(
  """
  SELECT *
  EXCLUDE (source_file, loaded_at)
  FROM raw.weather
  LIMIT 5;
  """
).df()

         date  county rainfall_mm temp_max_c temp_min_c
0  2019-01-01  Kisumu         0.0       28.2       16.4
1  2019-01-02  Kisumu         0.0       27.7       15.5
2  2019-01-03  Kisumu         0.0       29.4       15.5
3  2019-01-04  Kisumu         0.0       29.9       16.6
4  2019-01-05  Kisumu         0.0       28.4       15.9

**Cleaning Issues:**
*   Different `date` formats.
*   Inconsistent spelling formats in `county` col.
*   Possible erroneous `rainfall_mm` readings of -999.
*   Some records have NULL values.
*   Some temperature readings are 99.9 C.
*   List item



**Cleaning Actions:**
*   Parse `date` to consistent format.
*   Convert `county` values to lowercase.
*   Turn trace `rainfall_mm` reading into 0.1mm.
*   Set all abnormal readings of rainfall and temperature to NULL.
*   Blank readings will be left as they are.

In [51]:
# Clean & transform ops
conn.sql("""
    CREATE OR REPLACE TABLE staging.weather AS
    WITH cleaned AS (
        SELECT
            parse_date(r."date") AS obs_date,
            clean_county(r.county) AS county,
            CASE WHEN lower(trim(r.rainfall_mm)) = 'trace' THEN 0.1
                 WHEN TRY_CAST(r.rainfall_mm AS DOUBLE) < 0 THEN NULL
                 ELSE TRY_CAST(r.rainfall_mm AS DOUBLE) END AS rainfall_mm,
            CASE WHEN TRY_CAST(r.temp_max_c AS DOUBLE) BETWEEN -5 AND 50
                 THEN TRY_CAST(r.temp_max_c AS DOUBLE) END AS tmax,
            CASE WHEN TRY_CAST(r.temp_min_c AS DOUBLE) BETWEEN -5 AND 50
                 THEN TRY_CAST(r.temp_min_c AS DOUBLE) END AS tmin,
            r.rowid AS _row
        FROM raw.weather r
    ),
    ranked AS (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY obs_date, county ORDER BY _row) AS rn
        FROM cleaned
    )
    SELECT
        obs_date,
        county,
        rainfall_mm,
        CASE WHEN tmax < tmin THEN tmin ELSE tmax END AS temp_max_c,   -- swap min & max temp if reversed
        CASE WHEN tmax < tmin THEN tmax ELSE tmin END AS temp_min_c
    FROM ranked
    WHERE rn = 1
""")

conn.sql("SELECT * FROM staging.weather ORDER BY county, obs_date LIMIT 5").df()

    obs_date   county  rainfall_mm  temp_max_c  temp_min_c
0 2019-01-01  Bungoma          0.0        26.6         NaN
1 2019-01-02  Bungoma          0.1        24.1        12.0
2 2019-01-03  Bungoma          0.0        24.8        14.6
3 2019-01-04  Bungoma          0.0        28.7        13.4
4 2019-01-05  Bungoma          0.0        26.8        14.9

### Check cleaning outcome.

In [52]:
# Let's check the table before and after transformations & no. of removed entries.
staging = ['farms', 'plantings', 'inputs', 'harvests', 'weather']

rows = []

for table in staging:
  raw_n = conn.sql(f"SELECT COUNT(*) FROM raw.{table}").fetchone()[0]
  staging_n = conn.sql(f"SELECT COUNT(*) FROM staging.{table}").fetchone()[0]
  rows.append(
      {
          'table': table,
          'raw_rows': raw_n,
          'staging_rows': staging_n,
          'removed': raw_n - staging_n
      }
  )

pd.DataFrame(rows)

       table  raw_rows  staging_rows  removed
0      farms       812           800       12
1  plantings      5377          5298       79
2     inputs      7009          6860      149
3   harvests      5014          4885      129
4    weather     19078         18984       94

Rows removed are the duplicates plus the orphan records.

In [53]:
# Save a copy of the database in Drive
in_colab = "google.colab" in sys.modules
drive_db = project_dir / "data" / "agri.duckdb"

if in_colab:
    drive_db.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(db_path, drive_db)
    print("Database backed up to:", drive_db)

Database backed up to: /content/drive/MyDrive/Agriculture_ELT/data/agri.duckdb

This stage outputs five clean tables in the `staging` schema (farms, plantings, inputs, harvests, weather) plus the cleaning functions which are all saved in the database. Notably, the `raw` schema remains unchanged.

## Marts Layer: Join and Build Features

> The staging tables are clean but still separate; they need to be linked before being fed into a model. The model needs one row per per season with yield per acre as the **target** and all **features** that might explain it.

> This stage builds that table `marts.yield_dataset` step by step. This is a continuation of the transformation stage using SQL.

### Connect to Database

> This opens the database from the previous stages and lists the expected tables from the staging schema.

In [54]:
# Bring database back from drive
if drive_db.exists():
  shutil.copy(drive_db, db_path)

assert db_path.exists(), "agric.duckdb not found. Run notebook first."

# Establish connection to database
conn = duckdb.connect(str(db_path))

# Check tables in staging schema
conn.sql(
    """
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema == 'staging'
    ORDER BY 1;
    """
).df()

  table_name
0      farms
1   harvests
2     inputs
3  plantings
4    weather

### Step 1: `marts.planting_base`

> Farm details from the `farms` table are joined with `plantings` details to provide base information. **Importantly**, in some cases planting area is larger that land size; this may be because of rounded off figures when cnverting hectares to acres. A 20% tolerance is allowed for such scenarios; any records that exceed the tolerance limit will be set to `NULL`.

In [64]:
conn.sql("SELECT * FROM staging.plantings LIMIT 2").df()

,planting_id,farm_id,season,season_year,season_type,crop,planting_date,seed_variety,certified_seed,area_planted_acres
0,P00017,F0003,2023-LR,2023,LR,maize,2023-03-20,local,False,0.9
1,P00041,F0007,2021-LR,2021,LR,beans,2021-04-04,local,False,0.9

In [70]:
conn.sql(
    """
    CREATE OR REPLACE TABLE marts.planting_base AS
    SELECT
      p.planting_id,
      p.farm_id,
      f.county,
      p.season,
      p.season_year,
      p.season_type,
      p.crop,
      p.planting_date,
      p.seed_variety,
      p.certified_seed,
      f.irrigated,
      f.soil_type,
      f.size_acres,
      CASE
        WHEN p.area_planted_acres IS NULL THEN NULL
        WHEN p.area_planted_acres IS NOT NULL AND p.area_planted_acres > 1.2 * f.size_acres THEN NULL
        ELSE p.area_planted_acres
      END AS area_planted_acres,
      CASE
        WHEN p.area_planted_acres IS NULL THEN 'missing'
        WHEN p.area_planted_acres IS NOT NULL AND p.area_planted_acres > 1.2 * f.size_acres THEN 'exceeds farm size'
        ELSE 'ok'
      END AS area_status
    FROM staging.plantings p
    JOIN staging.farms f USING(farm_id)
    """
)

conn.sql("SELECT area_status, COUNT(*) FROM marts.planting_base GROUP BY 1 ORDER BY 2 DESC").df()

         area_status  count_star()
0                 ok          5086
1            missing           146
2  exceeds farm size            66