# Project Overview
**Predictive Modeling in Agriculture: Crop Recommendation**

**Business Problem:**

A farmer wants to determine the most suitable crop to grow on a particular field based on soil conditions.

However, due to budget constraints, the farmer can only afford to measure four soil properties:

* Nitrogen (N)
* Phosphorous (P)
* Potassium (K)
* Soil pH

The objective is to determine **which of these soil measures provides the most useful information for predicting the appropriate crop**.

**Project Objective:**

Build a machine learning classification model to predict crop yield per farm per season (a regression problem).

## Extract & Load

> The source data is in loose CSV files outside any database; this stage loads the files into DuckDB's `raw` schema. This is the 'EL' in ELT; no cleaning is done at this stage; it is done in the next stage, within the database using SQL.

### Connect to DuckDB; create the schemas

In [2]:
# Import libraries & dependencies
import duckdb
import pandas as pd
from pathlib import Path
import sys, shutil

# Mount drive and specify path
try:
  # Running in Colab
  from google.colab import drive
  drive.mount('/content/drive/')
  project_dir = Path('/content/drive/MyDrive/Agriculture_ELT')
  db_path = Path('/content/agric_elt.duckdb')
except ImportError:
  # Running locally
  project_dir = Path('..')
  db_path = project_dir / 'data' / 'agric_elt.duckdb'

source_dir = project_dir / 'data'

print('Source folder exists:', source_dir.exists())
print(sorted(p.name for p in source_dir.glob("*.csv")))

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
Source folder exists: True
['farms.csv', 'harvests.csv', 'inputs.csv', 'plantings.csv', 'weather.csv']

In [3]:
# Connect to db and create schemas
conn = duckdb.connect(str(db_path))

conn.sql("CREATE SCHEMA IF NOT EXISTS raw")
conn.sql("CREATE SCHEMA IF NOT EXISTS staging")
conn.sql("CREATE SCHEMA IF NOT EXISTS marts")

conn.sql(
    "SELECT schema_name from information_schema.schemata WHERE schema_name IN ('raw', 'staging', 'marts')"
).df()

  schema_name
0       marts
1         raw
2     staging

### Load CSV files into `raw` as text.

> Read every column as `VARCHAR` to avoid altering data or load failure; keeping all records as text ensures nothing is lost or altered. Data types will be transformed appropriately in the next stage.
> Two columns are added to each table: source_file (where each row came from) and loaded_at (when it was loaded).

In [4]:
tables = ['farms', 'plantings', 'inputs', 'harvests', 'weather']

for name in tables:
  conn.sql(
      f"""
      CREATE OR REPLACE TABLE raw.{name} AS
      SELECT
        *,
        '{name}.csv' AS source_file,
        current_timestamp AS loaded_at
      FROM read_csv("{source_dir / (name + '.csv')}", header=true, all_varchar=true)
      """
  )

  print(f"loaded raw.{name}")

loaded raw.farms
loaded raw.plantings
loaded raw.inputs
loaded raw.harvests
loaded raw.weather

### Check & Validate Loading Stage

> Check every table's row count matches the no. of rows in corresponding CSV.

In [5]:
checks = []

for name in tables:
  in_db = conn.sql(f"SELECT COUNT(*) FROM raw.{name}").fetchone()[0]
  in_csv = len(pd.read_csv(source_dir / f'{name}.csv', dtype=str))
  checks.append(
      {
          'table': name,
          'rows_in_db': in_db,
          'rows_in_csv': in_csv,
          'match': in_db == in_csv
      }
  )

result = pd.DataFrame(checks)
assert result['match'].all(), "Row count differ between CSV and db!"
result

       table  rows_in_db  rows_in_csv  match
0      farms         812          812   True
1  plantings        5377         5377   True
2     inputs        7009         7009   True
3   harvests        5014         5014   True
4    weather       19078        19078   True

### Preview the raw data

In [6]:
for name in tables:
  print(f'raw.{name}')
  display(conn.sql(f"SELECT * EXCLUDE (source_file, loaded_at) FROM raw.{name} LIMIT 5").df())
  print('\n')

raw.farms

  farm_id       county size_acres  soil_type irrigated registration_date
0  F-0001     Kakamega  0.6 acres  clay loam        no        29/03/2020
1   F0002  Uasin Gishu       11.1       loam         N        2012-05-06
2   F0003         Meru        1.0       clay         N        2021-04-14
3   F0004         Meru        1.3      Sandy         N        13/11/2008
4   F0005        Narok        6.2  clay loam        No        2021-03-29

raw.plantings

,planting_id,farm_id,season,crop,planting_date,seed_variety,area_planted_acres
0,P00001,f0001,2020-LR,Maize,2020-03-28,H513,0.9
1,P00002,F0001,2023 Long Rains,Beans,"Apr 24, 2023",Local,0.3
2,P00003,F0001,2024 LR,Maize,18/04/2024,LOCAL,0.6
3,P00004,F0002,LR 2019,Maize,2019-03-14,DK8031,8.2
4,P00005,F0002,SR2019,Wheat,18/10/2019,Robin,4.7

raw.inputs

  input_id farm_id application_date   input_type quantity    unit cost_kes
0   I00001   F0001       2020-03-23       manure    300.0      Kg     1247
1   I00002   F0001       2024-04-18  DAP 18-46-0     30.0     kgs     4263
2   I00003   F0001       31/05/2024          CAN     24.0      kg     None
3   I00004   F0002       2019-03-14  DAP 18-46-0    410.0      kg     None
4   I00005   F0002       02/05/2019    Pesticide      7.5  litres     8521

raw.harvests

,harvest_id,farm_id,season,crop,harvest_date,yield_qty,yield_unit,notes
0,H00001,F0001,2023 LR,beans,24/07/2023,0.5,bags,None
1,H00002,F0001,2024 Long Rains,Maize,22/08/2024,5.7,bags,None
2,H00003,F0002,2019 Long Rains,Maize,2019-08-11,13.15,tonnes,None
3,H00004,F0002,2019 Short Rains,Wheat,19/02/2020,8.91,t,None
4,H00005,F0002,2020 LR,wheat,08/07/2020,6.94,MT,None

raw.weather

         date  county rainfall_mm temp_max_c temp_min_c
0  2019-01-01  Kisumu         0.0       28.2       16.4
1  2019-01-02  Kisumu         0.0       27.7       15.5
2  2019-01-03  Kisumu         0.0       29.4       15.5
3  2019-01-04  Kisumu         0.0       29.9       16.6
4  2019-01-05  Kisumu         0.0       28.4       15.9

### How messy is the data?

> Now that we have loaded the data successfully into the db, let's preview the messiness of the data.

In [7]:
# 1. Same crop name, different spelling formats.
conn.sql(
    """
      SELECT crop,
          COUNT(*) as count
      FROM raw.harvests
      GROUP BY 1
      ORDER BY 2 DESC
    """
).df()

           crop  count
0         Maize   1836
1         Beans   1028
2         Wheat    408
3       Sorghum    390
4         maize    294
5         MAIZE    161
6         beans    154
7          Corn    126
8        Maize     114
9         wheat     73
10         Bean     73
11        BEANS     71
12      sorghum     63
13       Beans      60
14      SORGHUM     37
15  Wheat grain     30
16     Sorghum      30
17        WHEAT     26
18       Sorgum     21
19       Wheat      19

In [8]:
# 2. Harvest yeilds in different formats
conn.sql(
    """
      SELECT yield_unit,
        COUNT(*) AS count
      FROM raw.harvests
      GROUP BY 1
      ORDER BY 2 DESC
    """
).df()

   yield_unit  count
0        bags   1642
1          kg   1039
2        Bags    568
3         bag    385
4          Kg    330
5      tonnes    282
6    90kg bag    212
7          KG    190
8         kgs    141
9        None     84
10          t     84
11         MT     57

In [9]:
# 3. Explore messiness in weather table
conn.sql(
    """
      SELECT rainfall_mm,
        COUNT(*) AS count
      FROM raw.weather
      WHERE TRY_CAST(rainfall_mm AS FLOAT) IS NULL OR TRY_CAST(rainfall_mm AS FLOAT) < 0
      GROUP BY 1
      ORDER BY 2 DESC
    """
).df()

  rainfall_mm  count
0        None    420
1       trace    135
2        -999     75

This stage outputs an `agric_elt.duckdb` with fuve tables in the `raw` schema identical to the source CSV files. The `.duckdb` file is git-ignored since re-running the notebook rebuilds the file.

## Staging: Data Transformations

> The `raw` tables are too messy to be joined and analyzed reliably. This stage turns each `raw.*` table into a clean, analysis-ready `staging.*` table using SQL.

> This stage represents the T in 'ELT' and the tranformations happen inside the database without modifing the `raw` schema.

In [10]:
# Preview the tables in raw schema
conn.sql(
    """
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema == 'raw'
      ORDER BY 1
    """
).df()

  table_name
0      farms
1   harvests
2     inputs
3  plantings
4    weather

### Reusable Cleaning Functions

> There are fields that appear in all five tables eg fields IDs and dates; we will define SQL functions to reuse across all tables.

In [11]:
# Farms IDS: Standardise spelling formats e.g f0002, F-0002 and "F0002 " >> become F0002
conn.sql(
    """
      CREATE OR REPLACE MACRO clean_farm_id(x) AS
        upper(regexp_replace(trim(x), '[^A-Za-z0-9]', '', 'g'))
    """
)

# Correct misspelt crop names; aliases such as corn should be tranformed to maize
conn.sql(
    """
      CREATE OR REPLACE MACRO clean_crop(x) AS
        CASE lower(trim(x))
          WHEN 'corn' THEN 'maize'
          WHEN 'bean' THEN 'beans'
          WHEN 'sorgum' THEN 'sorghum'
          WHEN 'wheat grain' THEN 'wheat'
          ELSE lower(trim(x))
        END
    """
)

# Standardize county names
# County names
conn.sql("""
    CREATE OR REPLACE MACRO clean_county(x) AS
        CASE lower(replace(trim(x), '-', ' '))
            WHEN 'kisumu' THEN 'Kisumu'
            WHEN 'nakuru' THEN 'Nakuru'
            WHEN 'uasin gishu' THEN 'Uasin Gishu'
            WHEN 'kakamega' THEN 'Kakamega'
            WHEN 'machakos' THEN 'Machakos'
            WHEN 'meru' THEN 'Meru'
            WHEN 'bungoma' THEN 'Bungoma'
            WHEN 'narok' THEN 'Narok'
        END
""")

# Varying season labels:
# '2023 Long Rains', 'LR2023', '2023 LR' e.t.c >> become 2023-LR
conn.sql(
    """
      CREATE OR REPLACE MACRO clean_season(x) AS
        regexp_extract(x, '[0-9]{4}', 0) || '-' ||
        CASE WHEN lower(x) LIKE '%short%' OR upper(x) LIKE '%SR%' THEN 'SR'
             WHEN lower(x) LIKE '%long%' OR upper(x) LIKE '%LR%' THEN 'LR'
        END
    """
)

# Clean and standardize date formats
conn.sql(
    """
      CREATE OR REPLACE MACRO parse_date(x) AS
        CAST(COALESCE(
            TRY_STRPTIME(x, '%Y-%m-%d'),
            TRY_STRPTIME(x, '%d/%m/%Y'),
            TRY_STRPTIME(x, '%d-%b-%y'),
            TRY_STRPTIME(x, '%b %d, %Y')
        ) AS Date)
    """
)

# Quick test
conn.sql(
    """
      SELECT clean_farm_id('f-0005 ') AS farm_id,
        clean_crop('corn') AS crop,
        clean_season('2023 Long Rains') AS season,
        parse_date('14-Sep-26') AS date_1,
        parse_date('2021-03-21') AS date_2
    """
).df()

  farm_id   crop   season     date_1     date_2
0   F0005  maize  2023-LR 2026-09-14 2021-03-21

### Clean & Transform `farms` table.

In [12]:
# Preview & inspect raw.farms table
conn.sql(
    """
    SELECT *
    EXCLUDE (source_file, loaded_at)
    FROM raw.farms
    LIMIT 5
    """
).df()

  farm_id       county size_acres  soil_type irrigated registration_date
0  F-0001     Kakamega  0.6 acres  clay loam        no        29/03/2020
1   F0002  Uasin Gishu       11.1       loam         N        2012-05-06
2   F0003         Meru        1.0       clay         N        2021-04-14
3   F0004         Meru        1.3      Sandy         N        13/11/2008
4   F0005        Narok        6.2  clay loam        No        2021-03-29

In [13]:
# Check for duplicates
conn.sql(
    """
    SELECT farm_id,
      COUNT(*) AS occurrence_count
    FROM raw.farms
    GROUP BY 1
    HAVING occurrence_count > 1
    """
).df()

  farm_id  occurrence_count
0   F0112                 2
1   F0176                 2
2   F0256                 2
3   F0511                 2
4   F0643                 2
5   F0009                 2
6   F0243                 2
7   F0431                 2
8   F0736                 2
9   F0765                 2

In [14]:
# Inspect the duplicates further
conn.sql(
    """
    SELECT *
    EXCLUDE (source_file, loaded_at)
      FROM raw.farms
      WHERE farm_id IN ('F0643', 'F0256', 'F0431')
      ORDER BY farm_id
    """
).df()

# VERDICT: The records are clearly duplicated; they should be dropped from the table.

  farm_id    county size_acres  soil_type irrigated registration_date
0   F0256    Nakuru        5.4  clay loam         0        2012-12-30
1   F0256    Nakuru  5.4 acres  clay loam         N        30/12/2012
2   F0431      Meru        1.2      Sandy         N        2018-11-29
3   F0431      Meru        1.2      sandy         N        2018-11-29
4   F0643  machakos        4.6       loam         N        2010-11-16
5   F0643  Machakos        4.6       loam        No        16/11/2010

**Cleaning Issues:**

*   `farm_id` in different formats.
*   Duplicates in `farm_id` column.
*   `county` & `soil_type` in varying case fromats.
*   `size_acres` in varying units (acres and hectares).
*   Different `registration_date` formats.
*   `irrigated` assigned different flags: N, Y, no, Yes, 1.


> **Cleaning Actions:** clean the IDs and remove duplicates, convert sizes to acres (1 ha = 2.471 acres), turn the irrigation flag into a true/false value, & standardise soil type and county. Missing soil types stay `NULL`.

In [15]:
# Cleaning transformations
conn.sql("""
    CREATE OR REPLACE TABLE staging.farms AS
    WITH cleaned AS (
        SELECT
            clean_farm_id(r.farm_id) AS farm_id,
            clean_county(r.county) AS county,
            ROUND(
                TRY_CAST(regexp_extract(r.size_acres, '[0-9]+[.]?[0-9]*', 0) AS DOUBLE)
                * CASE WHEN lower(r.size_acres) LIKE '%ha%' THEN 2.471 ELSE 1 END
            , 1)                      AS size_acres,
            CASE lower(replace(trim(r.soil_type), '-', ' '))
                WHEN 'loamy' THEN 'loam'
                ELSE NULLIF(lower(replace(trim(r.soil_type), '-', ' ')), '')
            END                       AS soil_type,
            CASE lower(trim(r.irrigated))
                WHEN 'y' THEN TRUE  WHEN 'yes' THEN TRUE  WHEN '1' THEN TRUE
                WHEN 'n' THEN FALSE WHEN 'no'  THEN FALSE WHEN '0' THEN FALSE
            END                       AS irrigated,
            parse_date(r.registration_date) AS registration_date,
            r.rowid                   AS _row
        FROM raw.farms r
    ),
    ranked AS (
        SELECT *,
          ROW_NUMBER() OVER (PARTITION BY farm_id ORDER BY _row) AS rn
        FROM cleaned
    )
    SELECT farm_id, county, size_acres, soil_type, irrigated, registration_date
    FROM ranked
    WHERE rn = 1
""")

conn.sql("SELECT * FROM staging.farms LIMIT 5").df()

  farm_id    county  size_acres   soil_type  irrigated registration_date
0   F0032      Meru         1.7  sandy loam      False        2017-07-31
1   F0041  Kakamega         0.6  sandy loam      False        2009-10-11
2   F0053  Kakamega         1.4   clay loam      False        2020-09-07
3   F0062    Kisumu         1.6   clay loam      False        2017-05-30
4   F0081      Meru         1.0  sandy loam      False        2011-08-21

### Clean & Transform `plantings` table

In [16]:
# Preview & inspect raw.plantings table
conn.sql(
    """
    SELECT *
      EXCLUDE (source_file, loaded_at)
    FROM raw.plantings
    LIMIT 5
    """
).df()

,planting_id,farm_id,season,crop,planting_date,seed_variety,area_planted_acres
0,P00001,f0001,2020-LR,Maize,2020-03-28,H513,0.9
1,P00002,F0001,2023 Long Rains,Beans,"Apr 24, 2023",Local,0.3
2,P00003,F0001,2024 LR,Maize,18/04/2024,LOCAL,0.6
3,P00004,F0002,LR 2019,Maize,2019-03-14,DK8031,8.2
4,P00005,F0002,SR2019,Wheat,18/10/2019,Robin,4.7

In [17]:
# Check for duplicates in planting_id
conn.sql(
    """
    SELECT COUNT(*) total_duplicates
    FROM
      (SELECT planting_id,
        COUNT(*) AS occurrence_count
      FROM raw.plantings
      GROUP BY 1
      HAVING occurrence_count > 1) AS sub
    """
).df()

   total_duplicates
0                79

In [18]:
# Inspect the duplicates further
conn.sql(
    """
    SELECT *
    EXCLUDE (source_file, loaded_at)
      FROM raw.plantings
      WHERE planting_id IN ('P04938', 'P04226', 'P00208')
      ORDER BY planting_id
    """
).df()

# VERDICT: Duplicated farm_ids contain similar data with different input formats;
# duplicates will be dropped from the table.

,planting_id,farm_id,season,crop,planting_date,seed_variety,area_planted_acres
0,P00208,F0033,2020 Short Rains,Maize,2020-11-20,local,0.9
1,P00208,F0033,2020 Short Rains,Maize,20/11/2020,local,0.9
2,P04226,F0637,2024 Long Rains,MAIZE,2024-03-19,landrace,3.6
3,P04226,F0637,2024 LR,Maize,19/03/2024,local,None
4,P04938,F0747,2024-LR,Maize,2024-04-01,local,1.1
5,P04938,F0747,2024 long rains,Maize,2024-04-01,Local,1.1

In [19]:
# Missing values in seed_variety col
conn.sql(
    """
    SELECT COUNT(*) AS seed_variety_nulls
    FROM
      (SELECT *
      FROM raw.plantings
      WHERE seed_variety IS NULL) AS sub
    """
).df()

   seed_variety_nulls
0                 329

**Cleaning Issues:**
*   Duplicated records in `planting_id`.
*   `farm_id`, `season` & `planting_date` in varying formats.
*   `seed_variety` == Local have varying spelling formats. Landrace variety is also a local variety.
*   Missing values in `seed_variety`.
*   Crop names have different spellings.

**Cleaning Actions:**
*   Standardise `season`, `crop`, `seed_variety`.
*   Group the local-seed spellings.
*   Parse `planting_date`.
*   All local `seed_variety` to be flagged as not certified.

In [20]:
# Clean & transform ops
conn.sql("""
    CREATE OR REPLACE TABLE staging.plantings AS
    WITH cleaned AS (
        SELECT
            r.planting_id,
            clean_farm_id(r.farm_id) AS farm_id,
            clean_season(r.season) AS season,
            clean_crop(r.crop) AS crop,
            parse_date(r.planting_date) AS planting_date,
            CASE WHEN lower(trim(r.seed_variety)) IN ('local', 'landrace') THEN 'local'
                 ELSE NULLIF(trim(r.seed_variety), '')
            END AS seed_variety,
            TRY_CAST(r.area_planted_acres AS DOUBLE) AS area_planted_acres,
            r.rowid AS _row
        FROM raw.plantings r
    ),
    ranked AS (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY planting_id ORDER BY _row) AS rn
        FROM cleaned
    )
    SELECT
        planting_id,
        farm_id,
        season,
        CAST(split_part(season, '-', 1) AS INTEGER) AS season_year,
        split_part(season, '-', 2) AS season_type,
        crop,
        planting_date,
        seed_variety,
        CASE WHEN seed_variety IS NULL THEN NULL
             WHEN seed_variety = 'local' THEN FALSE
             ELSE TRUE END AS certified_seed,
        area_planted_acres
    FROM ranked
    WHERE rn = 1
      AND farm_id IN (SELECT farm_id FROM staging.farms)
""")

conn.sql("SELECT * FROM staging.plantings LIMIT 5").df()

,planting_id,farm_id,season,season_year,season_type,crop,planting_date,seed_variety,certified_seed,area_planted_acres
0,P00017,F0003,2023-LR,2023,LR,maize,2023-03-20,local,False,0.9
1,P00041,F0007,2021-LR,2021,LR,beans,2021-04-04,local,False,0.9
2,P00053,F0008,2023-SR,2023,SR,maize,2023-10-03,H513,True,3.8
3,P00054,F0008,2024-SR,2024,SR,wheat,2024-10-31,Robin,True,5.0
4,P00078,F0012,2024-LR,2024,LR,maize,2024-03-20,PH4,True,0.7

### Clean & Transform inputs table

In [21]:
# Preview raw.inputs table
conn.sql(
    """
    SELECT *
      EXCLUDE (source_file, loaded_at)
    FROM raw.inputs
    LIMIT 5;
    """
).df()

  input_id farm_id application_date   input_type quantity    unit cost_kes
0   I00001   F0001       2020-03-23       manure    300.0      Kg     1247
1   I00002   F0001       2024-04-18  DAP 18-46-0     30.0     kgs     4263
2   I00003   F0001       31/05/2024          CAN     24.0      kg     None
3   I00004   F0002       2019-03-14  DAP 18-46-0    410.0      kg     None
4   I00005   F0002       02/05/2019    Pesticide      7.5  litres     8521

In [22]:
# Explore duplicates in input_id
conn.sql(
    """
    SELECT COUNT(*) AS total_duplicates
    FROM
      (SELECT input_id,
        COUNT(input_id) AS occurrence_count
      FROM raw.inputs
      GROUP BY 1
      HAVING occurrence_count > 1) AS sub
    """
).df()

   total_duplicates
0                83

In [23]:
# Explore the duplicates further
conn.sql(
    """
    SELECT *
      EXCLUDE (source_file, loaded_at)
    FROM raw.inputs
    WHERE input_id IN ('I00233', 'I00405', 'I06788')
    ORDER BY input_id
    """
).df()

# VERDICT: Remove duplicated records.

  input_id farm_id application_date input_type quantity  unit cost_kes
0   I00233   F0030        17-May-19        can     55.0   kgs     4480
1   I00233   F0030       2019-05-17        CAN     55.0    kg     4480
2   I00405   F0048       2023-11-13       Urea    155.0    kg    19763
3   I00405   F0048       2023-11-13       Urea    155.0    kg    19763
4   I06788   F0783     Mar 06, 2022        DAP      1.6  bags     9021
5   I06788   F0783       2022-03-06        DAP      1.6  Bags     None

**Cleaning Issues:**
*   `application_date` in different formats.
*   `input_type` in varying formats: e.g DAP, dap, CAN, CAN(top dress).
*   Different `unit` formats e.g bags, Bags, 50kg bag, kg, KG.
*   `farm_id` in varying formats e.g f0127, F0305.
*   Some values `cost_kes` are in text and NONE formats.



**Cleaning Actions:**
*   Parse `application_date`.
*   Standadise `input_type`, & `farm_id`.
*   Convert quantities to a single unit: kg for solids (a fertilizer bag = 50 kg) and litres for liquids. When the unit is missing the quantity is left as NULL.
*   Map every `input_type` to one category (DAP, CAN, Urea, Manure, Pesticide)

In [24]:
# Clean & transform ops
conn.sql("""
    CREATE OR REPLACE TABLE staging.inputs AS
    WITH cleaned AS (
        SELECT
            r.input_id,
            clean_farm_id(r.farm_id) AS farm_id,
            parse_date(r.application_date) AS application_date,
            CASE
                WHEN lower(trim(r.input_type)) LIKE 'dap%' THEN 'DAP'
                WHEN lower(trim(r.input_type)) LIKE 'can%' THEN 'CAN'
                WHEN lower(trim(r.input_type)) LIKE 'urea%' THEN 'Urea'
                WHEN lower(trim(r.input_type)) LIKE 'manure%'
                  OR lower(trim(r.input_type)) IN ('fym')
                  OR lower(trim(r.input_type)) LIKE 'farmyard%' THEN 'Manure'
                WHEN lower(trim(r.input_type)) LIKE 'pesticide%'
                  OR lower(trim(r.input_type)) LIKE 'duduthrin%'
                  OR lower(trim(r.input_type)) LIKE 'insecticide%' THEN 'Pesticide'
            END                              AS input_type,
            TRY_CAST(r.quantity AS DOUBLE)   AS quantity_raw,
            CASE
                WHEN lower(trim(r.unit)) IN ('kg', 'kgs') THEN 'kg'
                WHEN lower(trim(r.unit)) IN ('bag', 'bags', '50kg bag') THEN 'bags'
                WHEN lower(trim(r.unit)) IN ('t', 'tonnes', 'mt') THEN 'tonnes'
                WHEN lower(trim(r.unit)) IN ('l', 'litres', 'ltrs') THEN 'litres'
                WHEN lower(trim(r.unit)) = 'ml' THEN 'ml'
            END AS unit_raw,
            TRY_CAST(regexp_replace(r.cost_kes, '[^0-9.]', '', 'g') AS DOUBLE) AS cost_kes,
            r.rowid AS _row
        FROM raw.inputs r
    ),
    ranked AS (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY input_id ORDER BY _row) AS rn
        FROM cleaned
    )
    SELECT
        input_id,
        farm_id,
        application_date,
        input_type,
        CASE WHEN input_type IN ('DAP', 'CAN', 'Urea') THEN 'fertilizer'
             WHEN input_type = 'Manure' THEN 'manure'
             WHEN input_type = 'Pesticide' THEN 'pesticide'
        END AS input_group,
        CASE unit_raw
            WHEN 'kg' THEN quantity_raw
            WHEN 'bags' THEN quantity_raw * 50
            WHEN 'tonnes' THEN quantity_raw * 1000
            WHEN 'litres' THEN quantity_raw
            WHEN 'ml' THEN quantity_raw / 1000
        END AS quantity,
        CASE WHEN unit_raw IN ('kg', 'bags', 'tonnes') THEN 'kg'
             WHEN unit_raw IN ('litres', 'ml') THEN 'litres'
        END AS unit,
        cost_kes
    FROM ranked
    WHERE rn = 1
      AND farm_id IN (SELECT farm_id FROM staging.farms)
""")

conn.sql("SELECT * FROM staging.inputs LIMIT 5").df()

,input_id,farm_id,application_date,input_type,input_group,quantity,unit,cost_kes
0,I00039,F0005,2022-03-11,DAP,fertilizer,200.0,kg,30048.0
1,I00054,F0007,2021-03-30,Manure,manure,1800.0,kg,6295.0
2,I00068,F0008,2022-11-03,DAP,fertilizer,315.0,kg,46008.0
3,I00084,F0009,2023-04-26,CAN,fertilizer,150.0,kg,14627.0
4,I00161,F0019,2020-03-07,Manure,manure,5600.0,kg,19878.0

### Clean & Transform harvests table

In [25]:
# Preview raw.harvests table
conn.sql(
    """
    SELECT *
      EXCLUDE (source_file, loaded_at)
    FROM raw.harvests
    LIMIT 5;
    """
).df()

,harvest_id,farm_id,season,crop,harvest_date,yield_qty,yield_unit,notes
0,H00001,F0001,2023 LR,beans,24/07/2023,0.5,bags,None
1,H00002,F0001,2024 Long Rains,Maize,22/08/2024,5.7,bags,None
2,H00003,F0002,2019 Long Rains,Maize,2019-08-11,13.15,tonnes,None
3,H00004,F0002,2019 Short Rains,Wheat,19/02/2020,8.91,t,None
4,H00005,F0002,2020 LR,wheat,08/07/2020,6.94,MT,None

In [26]:
# Explore yield_qty; some quantities are negative.
conn.sql(
    """
    SELECT yield_qty
    FROM raw.harvests
    WHERE (yield_qty::FLOAT) < 0
    LIMIT 5;
    """
).df()

  yield_qty
0     -27.8
1      -7.5
2      -0.5
3     -37.3
4     -88.4

In [27]:
# Explore null values in yield_qty
conn.sql(
    """
    SELECT COUNT(*) AS null_count
    FROM
      (SELECT yield_qty
      FROM raw.harvests
      WHERE yield_qty IS NULL) AS sub;
    """
).df()

   null_count
0         105

In [28]:
# Explore no. of duplicates in harvest_id
conn.sql(
    """
    SELECT COUNT(*) AS total_duplicates
    FROM
      (SELECT harvest_id,
        COUNT(harvest_id) AS occurrence_count
      FROM raw.harvests
      GROUP BY 1
      HAVING occurrence_count > 1) AS sub
    """
).df()

   total_duplicates
0                74

In [29]:
# Investigate the duplicates further
conn.sql(
    """
    SELECT *
      EXCLUDE ('source_file', 'loaded_at')
    FROM raw.harvests
    WHERE harvest_id IN ('H00043', 'H00374', 'H00349')
    ORDER BY 1
    """
).df()

# VERDICT: Duplicates are errorneous and should be dropped.

,harvest_id,farm_id,season,crop,harvest_date,yield_qty,yield_unit,notes
0,H00043,F0008,2019 Long Rains,Wheat,2019-08-06,12649.0,Kg,None
1,H00043,F0008,2019-LR,Wheat,06/08/2019,12649.0,Kg,None
2,H00349,F0057,2019 long rains,maize,2019-07-28,8.7,Bags,None
3,H00349,F0057,LR 2019,Corn,28/07/2019,-8.7,bags,None
4,H00374,F0060,2021 SR,Maize,2022-02-28,12.0,bags,None
5,H00374,F0060,2021 Short Rains,Maize,2022-02-28,12.0,bags,None

**Cleaning Issues:**
*   `farm_id`, `harvest_date` & `season` in varying formats.
*   Duplicated records in `harvest_id`.
*   Different spellings in `crop`.
*   Yields in varying units: kg, bags (90 kg) or tonnes
*   `yield_qty` have negative and null values.

**Cleaning Actions:**
*   Standardise `farm_id`, `harvest_date` & `season`.
*   Make `crop` spellings uniform.
*   Drop duplicates in `harvest_id`.
*   Convert every yield to kgs in a new yield_kg column (keep the original quantity and unit for reference).
*   Set negative yields to NULL.

In [30]:
# Clean & tranformations ops
conn.sql("""
    CREATE OR REPLACE TABLE staging.harvests AS
    WITH cleaned AS (
        SELECT
            r.harvest_id,
            clean_farm_id(r.farm_id) AS farm_id,
            clean_season(r.season) AS season,
            clean_crop(r.crop) AS crop,
            parse_date(r.harvest_date) AS harvest_date,
            CASE WHEN TRY_CAST(r.yield_qty AS DOUBLE) < 0 THEN NULL
                 ELSE TRY_CAST(r.yield_qty AS DOUBLE) END AS yield_qty,
            CASE
                WHEN lower(trim(r.yield_unit)) IN ('kg', 'kgs') THEN 'kg'
                WHEN lower(trim(r.yield_unit)) IN ('bag', 'bags', '90kg bag') THEN 'bags'
                WHEN lower(trim(r.yield_unit)) IN ('t', 'tonnes', 'mt') THEN 'tonnes'
            END AS yield_unit,
            NULLIF(lower(trim(r.notes)), '') AS notes,
            r.rowid AS _row
        FROM raw.harvests r
    ),
    ranked AS (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY harvest_id ORDER BY _row) AS rn
        FROM cleaned
    )
    SELECT
        harvest_id,
        farm_id,
        season,
        CAST(split_part(season, '-', 1) AS INTEGER) AS season_year,
        split_part(season, '-', 2) AS season_type,
        crop,
        harvest_date,
        yield_qty,
        yield_unit,
        CASE yield_unit
            WHEN 'kg' THEN yield_qty
            WHEN 'bags' THEN yield_qty * 90
            WHEN 'tonnes' THEN yield_qty * 1000
        END AS yield_kg,
        notes
    FROM ranked
    WHERE rn = 1
      AND farm_id IN (SELECT farm_id FROM staging.farms)
""")

conn.sql("SELECT * FROM staging.harvests LIMIT 5").df()

,harvest_id,farm_id,season,season_year,season_type,crop,harvest_date,yield_qty,yield_unit,yield_kg,notes
0,H00022,F0004,2022-LR,2022,LR,beans,2022-06-19,2.1,bags,189.0,None
1,H00024,F0005,2020-LR,2020,LR,maize,2020-08-05,237.0,kg,237.0,crop failure
2,H00046,F0008,2020-SR,2020,SR,maize,2021-04-01,9443.0,kg,9443.0,None
3,H00048,F0008,2022-LR,2022,LR,beans,2022-06-22,969.0,kg,969.0,None
4,H00050,F0008,2023-SR,2023,SR,maize,2024-02-02,5318.0,kg,5318.0,partial harvest

### Clean & Transform weather table

In [31]:
# Preview raw.weather table
conn.sql(
  """
  SELECT *
  EXCLUDE (source_file, loaded_at)
  FROM raw.weather
  LIMIT 5;
  """
).df()

         date  county rainfall_mm temp_max_c temp_min_c
0  2019-01-01  Kisumu         0.0       28.2       16.4
1  2019-01-02  Kisumu         0.0       27.7       15.5
2  2019-01-03  Kisumu         0.0       29.4       15.5
3  2019-01-04  Kisumu         0.0       29.9       16.6
4  2019-01-05  Kisumu         0.0       28.4       15.9

**Cleaning Issues:**
*   Different `date` formats.
*   Inconsistent spelling formats in `county` col.
*   Possible erroneous `rainfall_mm` readings of -999.
*   Some records have NULL values.
*   Some temperature readings are 99.9 C.
*   List item



**Cleaning Actions:**
*   Parse `date` to consistent format.
*   Convert `county` values to lowercase.
*   Turn trace `rainfall_mm` reading into 0.1mm.
*   Set all abnormal readings of rainfall and temperature to NULL.
*   Blank readings will be left as they are.

In [32]:
# Clean & transform ops
conn.sql("""
    CREATE OR REPLACE TABLE staging.weather AS
    WITH cleaned AS (
        SELECT
            parse_date(r."date") AS obs_date,
            clean_county(r.county) AS county,
            CASE WHEN lower(trim(r.rainfall_mm)) = 'trace' THEN 0.1
                 WHEN TRY_CAST(r.rainfall_mm AS DOUBLE) < 0 THEN NULL
                 ELSE TRY_CAST(r.rainfall_mm AS DOUBLE) END AS rainfall_mm,
            CASE WHEN TRY_CAST(r.temp_max_c AS DOUBLE) BETWEEN -5 AND 50
                 THEN TRY_CAST(r.temp_max_c AS DOUBLE) END AS tmax,
            CASE WHEN TRY_CAST(r.temp_min_c AS DOUBLE) BETWEEN -5 AND 50
                 THEN TRY_CAST(r.temp_min_c AS DOUBLE) END AS tmin,
            r.rowid AS _row
        FROM raw.weather r
    ),
    ranked AS (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY obs_date, county ORDER BY _row) AS rn
        FROM cleaned
    )
    SELECT
        obs_date,
        county,
        rainfall_mm,
        CASE WHEN tmax < tmin THEN tmin ELSE tmax END AS temp_max_c,   -- swap min & max temp if reversed
        CASE WHEN tmax < tmin THEN tmax ELSE tmin END AS temp_min_c
    FROM ranked
    WHERE rn = 1
""")

conn.sql("SELECT * FROM staging.weather ORDER BY county, obs_date LIMIT 5").df()

    obs_date   county  rainfall_mm  temp_max_c  temp_min_c
0 2019-01-01  Bungoma          0.0        26.6         NaN
1 2019-01-02  Bungoma          0.1        24.1        12.0
2 2019-01-03  Bungoma          0.0        24.8        14.6
3 2019-01-04  Bungoma          0.0        28.7        13.4
4 2019-01-05  Bungoma          0.0        26.8        14.9

### Check cleaning outcome.

In [33]:
# Let's check the table before and after transformations & no. of removed entries.
staging = ['farms', 'plantings', 'inputs', 'harvests', 'weather']

rows = []

for table in staging:
  raw_n = conn.sql(f"SELECT COUNT(*) FROM raw.{table}").fetchone()[0]
  staging_n = conn.sql(f"SELECT COUNT(*) FROM staging.{table}").fetchone()[0]
  rows.append(
      {
          'table': table,
          'raw_rows': raw_n,
          'staging_rows': staging_n,
          'removed': raw_n - staging_n
      }
  )

pd.DataFrame(rows)

       table  raw_rows  staging_rows  removed
0      farms       812           800       12
1  plantings      5377          5298       79
2     inputs      7009          6860      149
3   harvests      5014          4885      129
4    weather     19078         18984       94

Rows removed are the duplicates plus the orphan records.

In [34]:
# Save a copy of the database in Drive
in_colab = "google.colab" in sys.modules
drive_db = project_dir / "data" / "agri.duckdb"

if in_colab:
    drive_db.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(db_path, drive_db)
    print("Database backed up to:", drive_db)

Database backed up to: /content/drive/MyDrive/Agriculture_ELT/data/agri.duckdb

This stage outputs five clean tables in the `staging` schema (farms, plantings, inputs, harvests, weather) plus the cleaning functions which are all saved in the database. Notably, the `raw` schema remains unchanged.

## Marts Layer: Join and Build Features

> The staging tables are clean but still separate; they need to be linked before being fed into a model. The model needs one row per farm per season with yield per acre as the **target** and all **features** that explains it.

> This stage builds that table `marts.yield_dataset` step by step. This is a continuation of the transformation stage using SQL.

### Connect to Database

> This opens the database from the previous stages and lists the expected tables from the staging schema.

In [35]:
# Bring database back from drive
if drive_db.exists():
  shutil.copy(drive_db, db_path)

assert db_path.exists(), "agric.duckdb not found. Run notebook first."

# Establish connection to database
conn = duckdb.connect(str(db_path))

# Check tables in staging schema
conn.sql(
    """
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema == 'staging'
    ORDER BY 1;
    """
).df()

  table_name
0      farms
1   harvests
2     inputs
3  plantings
4    weather

### Step 1: `marts.planting_base`

> Farm details from the `farms` table are joined with `plantings` details to provide base information. **Importantly**, in some cases planting area is larger that land size; this may be because of rounded off figures when cnverting hectares to acres. A 20% tolerance is allowed for such scenarios; any records that exceed the tolerance limit will be set to `NULL`.

In [37]:
conn.sql(
    """
    CREATE OR REPLACE TABLE marts.planting_base AS
    SELECT
      p.planting_id,
      p.farm_id,
      f.county,
      p.season,
      p.season_year,
      p.season_type,
      p.crop,
      p.planting_date,
      p.seed_variety,
      p.certified_seed,
      f.irrigated,
      f.soil_type,
      f.size_acres,
      CASE
        WHEN p.area_planted_acres IS NULL THEN NULL
        WHEN p.area_planted_acres IS NOT NULL AND p.area_planted_acres > 1.2 * f.size_acres THEN NULL
        ELSE p.area_planted_acres
      END AS area_planted_acres,
      CASE
        WHEN p.area_planted_acres IS NULL THEN 'missing'
        WHEN p.area_planted_acres IS NOT NULL AND p.area_planted_acres > 1.2 * f.size_acres THEN 'exceeds farm size'
        ELSE 'ok'
      END AS area_status
    FROM staging.plantings p
    JOIN staging.farms f USING(farm_id)
    """
)

conn.sql(
    """
    SELECT area_status,
      COUNT(*) AS count
    FROM marts.planting_base
    GROUP BY 1
    ORDER BY 2 DESC;
    """
    ).df()

         area_status  count
0                 ok   5086
1            missing    146
2  exceeds farm size     66

###Step 2: marts.planting_weather

> Weather data is collected daily in each county but we will only consider data collected within 110 days (a crop's growing period) after the planting date of a crop. Daily weather data for each farm's county will be summarized as follows:

*   Total rainfall within the growing period: `season_rain_mm`.
*   No. of days with at least 1mm of rain: `rain_days`.
*   The longest run of consequtive days with less than 1 mm rainfall: `max_dry_spell_days`.
*   Maximum and minimum temperatures: `mean_tmax_c` & `mean_tmin_c`.

In [38]:
conn.sql("""
    CREATE OR REPLACE TABLE marts.planting_weather AS
    WITH days AS (                                   -- every weather day inside each planting's 110-day window
        SELECT b.planting_id, w.obs_date, w.rainfall_mm, w.temp_max_c, w.temp_min_c
        FROM marts.planting_base b
        JOIN staging.weather w
          ON w.county   = b.county
         AND w.obs_date >= b.planting_date
         AND w.obs_date <  b.planting_date + 110
    ),
    flagged AS (                                     -- query the dry runs
        SELECT *,
            CASE WHEN rainfall_mm < 1 THEN 1 ELSE 0 END AS is_dry,
            SUM(CASE WHEN rainfall_mm < 1 THEN 0 ELSE 1 END)
                OVER (PARTITION BY planting_id ORDER BY obs_date) AS run_id
        FROM days
    ),
    dry_spell AS (
        SELECT planting_id, MAX(run_length) AS max_dry_spell_days
        FROM (
            SELECT planting_id, run_id, SUM(is_dry) AS run_length
            FROM flagged
            GROUP BY planting_id, run_id
        )
        GROUP BY planting_id
    ),
    summary AS (
        SELECT
            planting_id,
            COUNT(*) AS window_days,
            COUNT(rainfall_mm) AS rain_obs_days,
            SUM(rainfall_mm) AS rain_sum_observed,
            COUNT(*) FILTER (WHERE rainfall_mm >= 1) AS rain_days,
            AVG(temp_max_c) AS mean_tmax_c,
            AVG(temp_min_c) AS mean_tmin_c
        FROM days
        GROUP BY planting_id
    )
    SELECT
        s.planting_id,
        s.window_days,
        s.rain_obs_days,
        CASE WHEN s.rain_obs_days >= 0.8 * s.window_days
             THEN ROUND(s.rain_sum_observed / s.rain_obs_days * s.window_days, 1)
        END AS season_rain_mm,
        s.rain_days,
        d.max_dry_spell_days,
        ROUND(s.mean_tmax_c, 1) AS mean_tmax_c,
        ROUND(s.mean_tmin_c, 1) AS mean_tmin_c
    FROM summary s
    JOIN dry_spell d USING (planting_id)
""")

conn.sql("""
    SELECT COUNT(*) AS plantings,
           MIN(window_days) AS min_window_days, MAX(window_days) AS max_window_days,
           COUNT(*) FILTER (WHERE season_rain_mm IS NULL) AS missing_rain_total,
           ROUND(AVG(season_rain_mm)) AS avg_season_rain_mm
    FROM marts.planting_weather
""").df()

,plantings,min_window_days,max_window_days,missing_rain_total,avg_season_rain_mm
0,5298,110,110,0,405.0

### Step 3: marts.planting inputs

> Input records have a `farm_id` and an `application_date` but no `planting_id`. We link each input to the planting on the same farm whose planting date is within 20 days before to 90 days after the application. The two seasons on a farm are months apart, so this window is unambiguous; if an input ever matches two plantings, it goes to the nearest one.

> **Extreme quantities**: a few quantities are far too large (an extra two zeros). Now that we know the planted area we can compute each application's rate per acre and compare it with the typical rate for that input. Anything over 3 times the median rate for its input type is treated as a data-entry error and left out of the totals, and counted in n_outlier_inputs_dropped.

> **Missing records:** about 10% of applications were never written down, and some records have no unit. We can't recover them, so an input without a usable record counts as zero applied. This adds noise thhat the model has to cope with.

In [51]:
conn.sql("""
    CREATE OR REPLACE TABLE marts.planting_inputs AS
    WITH linked AS (                                  -- attach each input to a planting (nearest one wins)
        SELECT
            i.input_id, i.input_type, i.input_group, i.quantity,
            b.planting_id, b.area_planted_acres,
            ROW_NUMBER() OVER (
                PARTITION BY i.input_id
                ORDER BY ABS(DATE_DIFF('day', b.planting_date, i.application_date))
            ) AS rn
        FROM staging.inputs i
        JOIN marts.planting_base b
          ON b.farm_id = i.farm_id
         AND i.application_date BETWEEN b.planting_date - 20 AND b.planting_date + 90
    ),
    rates AS (
        SELECT *, quantity / area_planted_acres AS rate_per_acre
        FROM linked
        WHERE rn = 1
    ),
    medians AS (                                      -- typical rate per acre for each input type
        SELECT input_type, MEDIAN(rate_per_acre) AS median_rate
        FROM rates
        WHERE rate_per_acre IS NOT NULL
        GROUP BY input_type
    ),
    checked AS (
        SELECT r.*,
               r.rate_per_acre > 3 * m.median_rate                         AS is_outlier,
               (r.rate_per_acre IS NOT NULL AND r.rate_per_acre <= 3 * m.median_rate) AS is_usable
        FROM rates r
        JOIN medians m USING (input_type)
    ),
    totals AS (
        SELECT
            b.planting_id,
            b.area_planted_acres,
            COUNT(c.input_id)                                                         AS n_input_records,
            COUNT(*) FILTER (WHERE c.is_outlier)                                      AS n_outlier_inputs_dropped,
            COUNT(*) FILTER (WHERE c.is_usable AND c.input_group = 'fertilizer')      AS n_fertilizer_applications,
            COALESCE(SUM(c.quantity) FILTER (WHERE c.is_usable AND c.input_group = 'fertilizer'), 0) AS fertilizer_kg,
            COALESCE(SUM(c.quantity) FILTER (WHERE c.is_usable AND c.input_group = 'manure'), 0)     AS manure_kg,
            COALESCE(SUM(c.quantity) FILTER (WHERE c.is_usable AND c.input_group = 'pesticide'), 0)  AS pesticide_litres
        FROM marts.planting_base b
        LEFT JOIN checked c USING (planting_id)
        GROUP BY b.planting_id, b.area_planted_acres
    )
    SELECT
        planting_id,
        n_input_records,
        n_outlier_inputs_dropped,
        n_fertilizer_applications,
        ROUND(fertilizer_kg   / area_planted_acres, 1) AS fertilizer_kg_per_acre,
        ROUND(manure_kg       / area_planted_acres, 1) AS manure_kg_per_acre,
        ROUND(pesticide_litres / area_planted_acres, 2) AS pesticide_litres_per_acre,
        manure_kg > 0         AS used_manure,
        pesticide_litres > 0  AS used_pesticide
    FROM totals
""")

conn.sql("""
    SELECT COUNT(*)                                   AS plantings,
           SUM(n_outlier_inputs_dropped)              AS outlier_inputs_dropped,
           COUNT(*) FILTER (WHERE n_input_records = 0) AS plantings_with_no_input_records,
           ROUND(AVG(fertilizer_kg_per_acre), 1)      AS avg_fertilizer_kg_per_acre
    FROM marts.planting_inputs
""").df()

,plantings,outlier_inputs_dropped,plantings_with_no_input_records,avg_fertilizer_kg_per_acre
0,5298,63.0,1362,32.8

In [56]:
conn.sql("SELECT * FROM marts.planting_base LIMIT 5").df()

,planting_id,farm_id,county,season,season_year,season_type,crop,planting_date,seed_variety,certified_seed,irrigated,soil_type,size_acres,area_planted_acres,area_status
0,P00017,F0003,Meru,2023-LR,2023,LR,maize,2023-03-20,local,False,False,clay,1.0,0.9,ok
1,P00041,F0007,Meru,2021-LR,2021,LR,beans,2021-04-04,local,False,False,loam,1.9,0.9,ok
2,P00053,F0008,Uasin Gishu,2023-SR,2023,SR,maize,2023-10-03,H513,True,True,clay loam,8.7,3.8,ok
3,P00054,F0008,Uasin Gishu,2024-SR,2024,SR,wheat,2024-10-31,Robin,True,True,clay loam,8.7,5.0,ok
4,P00078,F0012,Bungoma,2024-LR,2024,LR,maize,2024-03-20,PH4,True,False,sandy,1.4,0.7,ok

### Step 4: The Main Table `marts.yield_dataset`

> Join the three tables above to the harvest records to get one row per planting with the target variable `yield_kg_per_acre` as harvested kg / planted acres.

> For each crop, any yield per acre above 4 times that crop's median is treated as a data-entry error and set to `NULL`.

> **Note:** The col `exclusion_reason` says why a row can't be used for modelling (first reason that applies), and `use_for_modelling` is a simple true/false for the next stage.

> **Leakage:** The harvest notes (e.g. "drought") are written after the harvest, so they are deliberately not carried into this table. If fed into a model, this would result in leakage.

In [62]:
conn.sql("""
    CREATE OR REPLACE TABLE marts.yield_dataset AS
    WITH joined AS (
        SELECT
            b.*,
            w.season_rain_mm, w.rain_days, w.max_dry_spell_days, w.mean_tmax_c, w.mean_tmin_c,
            i.fertilizer_kg_per_acre, i.manure_kg_per_acre, i.pesticide_litres_per_acre,
            i.n_fertilizer_applications, i.used_manure, i.used_pesticide,
            i.n_outlier_inputs_dropped,
            h.harvest_id IS NOT NULL AS has_harvest_record,
            h.harvest_date,
            h.yield_kg,
            h.yield_kg / b.area_planted_acres AS yield_per_acre_unchecked
        FROM marts.planting_base b
        LEFT JOIN marts.planting_weather w USING (planting_id)
        LEFT JOIN marts.planting_inputs i USING (planting_id)
        LEFT JOIN staging.harvests h
               ON h.farm_id = b.farm_id AND h.season = b.season AND h.crop = b.crop
    ),
    crop_median AS (
        SELECT crop, MEDIAN(yield_per_acre_unchecked) AS median_yield
        FROM joined
        WHERE yield_per_acre_unchecked IS NOT NULL
        GROUP BY crop
    ),
    flagged AS (
        SELECT j.*, (j.yield_per_acre_unchecked > 4 * m.median_yield) AS is_suspect_yield
        FROM joined j
        JOIN crop_median m USING (crop)
    )
    SELECT
        planting_id, farm_id, county, season, season_year, season_type, crop,
        soil_type, irrigated, size_acres,
        planting_date, seed_variety, certified_seed,
        area_planted_acres, area_status,
        season_rain_mm, rain_days, max_dry_spell_days, mean_tmax_c, mean_tmin_c,
        fertilizer_kg_per_acre, n_fertilizer_applications, manure_kg_per_acre, used_manure,
        pesticide_litres_per_acre, used_pesticide, n_outlier_inputs_dropped,
        has_harvest_record, harvest_date, yield_kg,
        CASE WHEN is_suspect_yield THEN NULL
             ELSE ROUND(yield_per_acre_unchecked, 1) END AS yield_kg_per_acre,
        CASE
            WHEN NOT has_harvest_record        THEN 'no_harvest_record'
            WHEN yield_kg IS NULL              THEN 'unusable_yield'
            WHEN area_planted_acres IS NULL    THEN 'invalid_area'
            WHEN is_suspect_yield              THEN 'suspect_yield'
            WHEN season_rain_mm IS NULL        THEN 'missing_weather'
        END AS exclusion_reason,
        CASE
            WHEN NOT has_harvest_record        THEN FALSE
            WHEN yield_kg IS NULL              THEN FALSE
            WHEN area_planted_acres IS NULL    THEN FALSE
            WHEN is_suspect_yield              THEN FALSE
            WHEN season_rain_mm IS NULL        THEN FALSE
            ELSE TRUE
        END AS use_for_modelling
    FROM flagged
""")

conn.sql("SELECT * FROM marts.yield_dataset LIMIT 5").df()

,planting_id,farm_id,county,season,season_year,season_type,crop,soil_type,irrigated,size_acres,...,used_manure,pesticide_litres_per_acre,used_pesticide,n_outlier_inputs_dropped,has_harvest_record,harvest_date,yield_kg,yield_kg_per_acre,exclusion_reason,use_for_modelling
0,P00017,F0003,Meru,2023-LR,2023,LR,maize,clay,False,1.0,...,False,0.00,False,0,True,2023-07-16,1196.0,1328.9,None,True
1,P00041,F0007,Meru,2021-LR,2021,LR,beans,loam,False,1.9,...,True,0.00,False,0,True,2021-07-21,135.0,150.0,None,True
2,P00053,F0008,Uasin Gishu,2023-SR,2023,SR,maize,clay loam,True,8.7,...,True,0.76,True,0,True,2024-02-02,5318.0,1399.5,None,True
3,P00054,F0008,Uasin Gishu,2024-SR,2024,SR,wheat,clay loam,True,8.7,...,True,0.00,False,0,True,2025-03-27,7226.0,1445.2,None,True
4,P00078,F0012,Bungoma,2024-LR,2024,LR,maize,sandy,False,1.4,...,False,0.00,False,0,True,2024-08-03,756.0,1080.0,None,True

### Step 5: `marts_county_season_summary`

> A small aggregated table showing average yield per acre, rainfall and fertilizer for each county, crop and season. It is a typical "reporting" mart tool that could feed a dashboard, and it also gives a quick feel for the data.

In [87]:
conn.sql(
    """
    CREATE OR REPLACE TABLE marts.county_season_summary AS
    SELECT county,
      season,
      season_year,
      crop,
      COUNT(*) AS n_plantings,
      ROUND(AVG(yield_kg_per_acre)) AS avg_yield_per_acre,
      ROUND(AVG(season_rain_mm)) AS avg_rainfall_mm,
      ROUND(AVG(fertilizer_kg_per_acre)) AS avg_fertilizer_per_acre
    FROM marts.yield_dataset
    WHERE use_for_modelling
    GROUP BY 1,2,3,4
    """
)

# Summary stats for maize yield in Nakuru
conn.sql(
    """SELECT *
    FROM marts.county_season_summary
    WHERE county == 'Nakuru' AND crop == 'maize'
    ORDER BY avg_yield_per_acre DESC
    LIMIT 5
    """
).df()

,county,season,season_year,crop,n_plantings,avg_yield_per_acre,avg_rainfall_mm,avg_fertilizer_per_acre
0,Nakuru,2019-LR,2019,maize,20,1169.0,410.0,55.0
1,Nakuru,2020-LR,2020,maize,24,1060.0,463.0,27.0
2,Nakuru,2024-LR,2024,maize,25,1043.0,479.0,21.0
3,Nakuru,2022-LR,2022,maize,16,1041.0,576.0,32.0
4,Nakuru,2023-LR,2023,maize,29,989.0,333.0,56.0

### Checks and Validation

> Is every planting accounted for? Either it is usable for modelling, or it has one reason explainging why it isn't.

In [88]:
conn.sql("""
    SELECT COALESCE(exclusion_reason, 'KEPT: usable for modelling') AS outcome,
           COUNT(*) AS plantings,
           ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS pct
    FROM marts.yield_dataset
    GROUP BY 1
    ORDER BY plantings DESC
""").df()

                      outcome  plantings   pct
0  KEPT: usable for modelling       4451  84.0
1           no_harvest_record        413   7.8
2              unusable_yield        199   3.8
3                invalid_area        194   3.7
4               suspect_yield         41   0.8

### The target (yield per acre) vs crop:
> Ssummary stats for Yield per acre for the rows that will be used for modelling. Note that different crops have different yield levels.

In [89]:
conn.sql("""
    SELECT crop,
           COUNT(*)                                    AS n,
           ROUND(AVG(yield_kg_per_acre))               AS mean,
           ROUND(MEDIAN(yield_kg_per_acre))            AS median,
           ROUND(quantile_cont(yield_kg_per_acre, 0.05)) AS p05,
           ROUND(quantile_cont(yield_kg_per_acre, 0.95)) AS p95,
           ROUND(MAX(yield_kg_per_acre))               AS max
    FROM marts.yield_dataset
    WHERE use_for_modelling
    GROUP BY crop
    ORDER BY crop
""").df()

      crop     n   mean  median    p05     p95     max
0    beans  1221  254.0   246.0   90.0   454.0   724.0
1    maize  2257  834.0   802.0  320.0  1485.0  2791.0
2  sorghum   483  368.0   354.0  129.0   680.0   883.0
3    wheat   490  913.0   882.0  273.0  1608.0  2631.0

### Is there a signal for the model?

> Let's check whether the features that we engineered relate to the target variable in a logical way. For instance, more fertilizer is likely to increase a crop's yield.

In [100]:
# Let's check fertilizer vs yield per acre in maize.
# More fertilizer should mean more yield.
conn.sql(
    """
    SELECT CASE
      WHEN fertilizer_kg_per_acre = 0 THEN 'none'
      WHEN fertilizer_kg_per_acre < 40 THEN 'upto 40 kg/acre'
      WHEN fertilizer_kg_per_acre < 80 THEN 'upto 80 kg/acre'
      ELSE 'over 80 kg/acre'
      END AS fertilizer_band,
      COUNT(*) AS count,
      ROUND(AVG(yield_kg_per_acre)) AS avg_yield_per_acre
    FROM marts.yield_dataset
    WHERE crop == 'maize' AND use_for_modelling
    GROUP BY 1
    ORDER BY 3 DESC
    """
).df()

   fertilizer_band  count  avg_yield_per_acre
0  over 80 kg/acre    378               944.0
1  upto 80 kg/acre    870               893.0
2  upto 40 kg/acre    221               866.0
3             none    788               706.0

In [105]:
# Rainfall: Less rainfall should mean less yield.
# Too much rainfall can jeopardize yield per acre.
conn.sql(
    """
    SELECT CASE
      WHEN season_rain_mm < 300 THEN 'below 300 mm'
      WHEN season_rain_mm < 450 THEN '300 to 450 mm'
      WHEN season_rain_mm < 600 THEN '450 to 600 mm'
      WHEN season_rain_mm < 750 THEN '600 to 750 mm'
      ELSE 'above 750 mm'
      END AS rainfall_band,
      COUNT(*) as count,
      ROUND(AVG(yield_kg_per_acre)) AS avg_yield_per_acre
    FROM marts.yield_dataset
    GROUP BY 1
    ORDER BY 3 DESC
    """
).df()

   rainfall_band  count  avg_yield_per_acre
0  450 to 600 mm    969               793.0
1  300 to 450 mm   1658               713.0
2  600 to 750 mm    545               556.0
3   below 300 mm   1780               547.0
4   above 750 mm    346               369.0

In [106]:
# Save a copy to drive
if in_colab:
    drive_db.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(db_path, drive_db)
    print("Database backed up to:", drive_db)

Database backed up to: /content/drive/MyDrive/Agriculture_ELT/data/agri.duckdb